package com.example.aura.presentation.meetingdetail

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.aura.domain.model.ActionItem
import com.example.aura.domain.model.Decision
import com.example.aura.domain.model.Meeting
import com.example.aura.domain.model.MessageDraft
import com.example.aura.domain.model.PipelineStatus
import com.example.aura.domain.repository.MeetingRepository
import com.example.aura.domain.usecase.DispatchMessageUseCase
import com.example.aura.domain.usecase.RunPipelineUseCase
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

@HiltViewModel
class MeetingDetailViewModel @Inject constructor(
    private val meetingRepository: MeetingRepository,
    private val dispatchMessageUseCase: DispatchMessageUseCase,
    private val runPipelineUseCase: RunPipelineUseCase
) : ViewModel() {

    private val _meetingId = MutableStateFlow<UUID?>(null)

    private val _isReanalysing = MutableStateFlow(false)
    val isReanalysing: StateFlow<Boolean> = _isReanalysing.asStateFlow()

    val meeting: StateFlow<Meeting?> = _meetingId
        .filterNotNull()
        .flatMapLatest { id -> meetingRepository.getMeetingById(id) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), null)

    val actionItems: StateFlow<List<ActionItem>> = _meetingId
        .filterNotNull()
        .flatMapLatest { id -> meetingRepository.getActionItemsForMeeting(id) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val decisions: StateFlow<List<Decision>> = _meetingId
        .filterNotNull()
        .flatMapLatest { id -> meetingRepository.getDecisionsForMeeting(id) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    val drafts: StateFlow<List<MessageDraft>> = _meetingId
        .filterNotNull()
        .flatMapLatest { id -> meetingRepository.getMessageDraftsForMeeting(id) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), emptyList())

    fun setMeetingId(id: UUID) {
        _meetingId.value = id
    }

    fun dispatchMessage(draft: MessageDraft) {
        viewModelScope.launch {
            dispatchMessageUseCase.execute(draft)
        }
    }

    fun updateDraft(draft: MessageDraft) {
        viewModelScope.launch {
            meetingRepository.updateMessageDraft(draft)
        }
    }

    fun reAnalyse() {
        val currentMeeting = meeting.value ?: return
        viewModelScope.launch {
            _isReanalysing.value = true
            // Reset to processing state
            meetingRepository.updateMeeting(currentMeeting.copy(pipelineStatus = PipelineStatus.PROCESSING))
            runPipelineUseCase.execute(currentMeeting)
            _isReanalysing.value = false
        }
    }

    fun buildShareText(): String {
        val m = meeting.value ?: return ""
        val sb = StringBuilder()
        sb.appendLine("📋 ${m.title}")
        sb.appendLine()
        sb.appendLine("Summary:")
        sb.appendLine(m.summary ?: "—")
        sb.appendLine()
        if (decisions.value.isNotEmpty()) {
            sb.appendLine("✅ Decisions:")
            decisions.value.forEach { sb.appendLine("• ${it.decisionText}") }
            sb.appendLine()
        }
        if (actionItems.value.isNotEmpty()) {
            sb.appendLine("📌 Action Items:")
            actionItems.value.forEach { sb.appendLine("• [${it.owner ?: "?"}] ${it.task}") }
            sb.appendLine()
        }
        sb.appendLine("Generated by Aura — Agentic Meeting Intelligence")
        return sb.toString()
    }
}
